//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movieverse.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MediaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MediaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movieverse.Application.Resources.MediaResources", typeof(MediaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add media.
        /// </summary>
        public static string CouldNotAddMedia {
            get {
                return ResourceManager.GetString("CouldNotAddMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update media.
        /// </summary>
        public static string CouldNotUpdateMedia {
            get {
                return ResourceManager.GetString("CouldNotUpdateMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details too long.
        /// </summary>
        public static string DetailsTooLong {
            get {
                return ResourceManager.GetString("DetailsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid media type.
        /// </summary>
        public static string InvalidMediaType {
            get {
                return ResourceManager.GetString("InvalidMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media does not exist.
        /// </summary>
        public static string MediaDoesNotExist {
            get {
                return ResourceManager.GetString("MediaDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media is not movie.
        /// </summary>
        public static string MediaIsNotMovie {
            get {
                return ResourceManager.GetString("MediaIsNotMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media is not series.
        /// </summary>
        public static string MediaIsNotSeries {
            get {
                return ResourceManager.GetString("MediaIsNotSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media with title already exists.
        /// </summary>
        public static string MediaWithTitleAlreadyExists {
            get {
                return ResourceManager.GetString("MediaWithTitleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role does not exist.
        /// </summary>
        public static string RoleDoesNotExist {
            get {
                return ResourceManager.GetString("RoleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storyline too long.
        /// </summary>
        public static string StorylineTooLong {
            get {
                return ResourceManager.GetString("StorylineTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagline too long.
        /// </summary>
        public static string TaglineTooLong {
            get {
                return ResourceManager.GetString("TaglineTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical specs too long.
        /// </summary>
        public static string TechnicalSpecsTooLong {
            get {
                return ResourceManager.GetString("TechnicalSpecsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title too long.
        /// </summary>
        public static string TitleTooLong {
            get {
                return ResourceManager.GetString("TitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title too short.
        /// </summary>
        public static string TitleTooShort {
            get {
                return ResourceManager.GetString("TitleTooShort", resourceCulture);
            }
        }
    }
}
