//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movieverse.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movieverse.Application.Resources.PersonResources", typeof(PersonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be greater than zero.
        /// </summary>
        public static string AgeMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("AgeMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography is too long.
        /// </summary>
        public static string BiographyIsTooLong {
            get {
                return ResourceManager.GetString("BiographyIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create person.
        /// </summary>
        public static string CouldNotCreatePerson {
            get {
                return ResourceManager.GetString("CouldNotCreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is too long.
        /// </summary>
        public static string FirstNameIsTooLong {
            get {
                return ResourceManager.GetString("FirstNameIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunFacts are too long.
        /// </summary>
        public static string FunFactsAreTooLong {
            get {
                return ResourceManager.GetString("FunFactsAreTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid chart category.
        /// </summary>
        public static string InvalidChartCategory {
            get {
                return ResourceManager.GetString("InvalidChartCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is too long.
        /// </summary>
        public static string LastNameIsTooLong {
            get {
                return ResourceManager.GetString("LastNameIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person does not exist.
        /// </summary>
        public static string PersonDoesNotExist {
            get {
                return ResourceManager.GetString("PersonDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already have a personality.
        /// </summary>
        public static string UserAlreadyHavePersonality {
            get {
                return ResourceManager.GetString("UserAlreadyHavePersonality", resourceCulture);
            }
        }
    }
}
