//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movieverse.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movieverse.Application.Resources.UserResources", typeof(UserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be greater than 0.
        /// </summary>
        public static string AgeMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("AgeMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not change external login password.
        /// </summary>
        public static string CanNotChangeExternalLoginPassword {
            get {
                return ResourceManager.GetString("CanNotChangeExternalLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud not sign in.
        /// </summary>
        public static string CloudNotSignIn {
            get {
                return ResourceManager.GetString("CloudNotSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not confirmed.
        /// </summary>
        public static string EmailIsNotConfirmed {
            get {
                return ResourceManager.GetString("EmailIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or username already taken.
        /// </summary>
        public static string EmailOrUserNameAlreadyExist {
            get {
                return ResourceManager.GetString("EmailOrUserNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter age.
        /// </summary>
        public static string EnterAge {
            get {
                return ResourceManager.GetString("EnterAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter authenticator.
        /// </summary>
        public static string EnterAuthenticator {
            get {
                return ResourceManager.GetString("EnterAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter refresh token.
        /// </summary>
        public static string EnterRefreshToken {
            get {
                return ResourceManager.GetString("EnterRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user name.
        /// </summary>
        public static string EnterUserName {
            get {
                return ResourceManager.GetString("EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add roles.
        /// </summary>
        public static string FailedToAddRoles {
            get {
                return ResourceManager.GetString("FailedToAddRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to authenticate via Google.
        /// </summary>
        public static string FailedToAuthenticateViaGoogle {
            get {
                return ResourceManager.GetString("FailedToAuthenticateViaGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change email.
        /// </summary>
        public static string FailedToChangeEmail {
            get {
                return ResourceManager.GetString("FailedToChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change password.
        /// </summary>
        public static string FailedToChangePassword {
            get {
                return ResourceManager.GetString("FailedToChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change username.
        /// </summary>
        public static string FailedToChangeUsername {
            get {
                return ResourceManager.GetString("FailedToChangeUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login.
        /// </summary>
        public static string FailedToLogin {
            get {
                return ResourceManager.GetString("FailedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login with refresh token.
        /// </summary>
        public static string FailedToLoginWithRefreshToken {
            get {
                return ResourceManager.GetString("FailedToLoginWithRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register user.
        /// </summary>
        public static string FailedToRegisterUser {
            get {
                return ResourceManager.GetString("FailedToRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid grant type.
        /// </summary>
        public static string InvalidGrantType {
            get {
                return ResourceManager.GetString("InvalidGrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token.
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be the same.
        /// </summary>
        public static string PasswordsMustBeTheSame {
            get {
                return ResourceManager.GetString("PasswordsMustBeTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System administrator role cannot be added.
        /// </summary>
        public static string SystemAdministratorRoleCannotBeAdded {
            get {
                return ResourceManager.GetString("SystemAdministratorRoleCannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already have personality.
        /// </summary>
        public static string UserAlreadyHavePersonality {
            get {
                return ResourceManager.GetString("UserAlreadyHavePersonality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is system administrator.
        /// </summary>
        public static string UserIsSystemAdministrator {
            get {
                return ResourceManager.GetString("UserIsSystemAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User update failed.
        /// </summary>
        public static string UserUpdateFailed {
            get {
                return ResourceManager.GetString("UserUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong data format.
        /// </summary>
        public static string WrongDataFormat {
            get {
                return ResourceManager.GetString("WrongDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email format.
        /// </summary>
        public static string WrongEmailFormat {
            get {
                return ResourceManager.GetString("WrongEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in.
        /// </summary>
        public static string YouAreNotLoggedIn {
            get {
                return ResourceManager.GetString("YouAreNotLoggedIn", resourceCulture);
            }
        }
    }
}
